version: "3.9"
services:
    server:
        build: .
        ports:
            - "5000:5000"
        environment: 
            - TOKEN_KEY
            - WEB_SERVER_URL
            - WEB_SERVER_PORT
