version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.7
    steps:
      - checkout
      - run:
          name: Create test reports directory
          command: mkdir /tmp/test-artifacts
      - run:
          name: Setup Code Climate test-reporter
          command: |
              # download test reporter as a static binary
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter before-build
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install dependencies-dev
          command: pip install -r dev-requirements.txt
      - run:
          name: Running Tests
          command: coverage run -m unittest && coverage xml && coverage report -m
      - run:
          name: Update CodeClimate coverage report
          command: |
              ./cc-test-reporter after-build --exit-code $?
      - run:
          name: Running Flake8
          command: flake8
  trigger-main-repo-update:
    docker:
      - image: curlimages/curl
    steps:
      - run:
          name: Update main repo
          command: |
            curl --request POST 'https://circleci.com/api/v2/project/github/evbeda/edagames/pipeline' \
            --header "Circle-Token: ${CCI_API_TOKEN}" \
            --header 'Content-Type: application/json' \
            --data '{"parameters":{"update_submodule_server":true}}'
workflows:
  main:
    jobs:
      - build-and-test
      - trigger-main-repo-update:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
