EVENT_SEND_CHALLENGE = 'challenge'
EVENT_SEND_ERROR = 'error'
EVENT_SEND_YOUR_TURN = 'your_turn'
EVENT_LIST_USERS = 'list_users'
ACCEPT_CHALLENGE = 'accept_challenge'
MOVEMENTS = 'movements'
LIST_USERS = 'list_users'
